name: src
version: 0.0.1
appVersion: 0.0.1
description: This is a pre-generated chart.
home: https://github.com/helm/helm
icon: https://helm.sh/src/img/helm-logo.svg
keywords:
- these
- are
- keywords
maintainers:
- name: you
  email: you@company.io
sources:
- https://github.com/helm/helm
apiVersion: v1
engine: gotpl
deprecated: false
